export const SORT_STATUS = {
  DEFAULT: "",
  SP: "São Paulo",
  AC: "Acre",
  AL: "Alagoas",
  AP: "Amapá",
  AM: "Amazonas",
  BA: "Bahia",
  CE: "Ceará",
  ES: "Espírito Santo",
  GO: "Goiás",
  MA: "Maranhão",
  MT: "Mato Grosso",
  MS: "Mato Grosso do Sul",
  MG: "Minas Gerais",
  PA: "Pará",
  PB: "Paraíba",
  PR: "Paraná",
  PE: "Pernambuco",
  PI: "Piauí",
  RJ: "Rio de Janeiro",
  RN: "Rio Grande do Norte",
  RS: "Rio Grande do Sul",
  RO: "Rondônia",
  RR: "Roraima",
  SC: "Santa Catarina",
  SE: "Sergipe",
  TO: "Tocantins",
  DF: "Distrito Federal",
};
export const DESTINY = {
  DEFAULT: "",
  SP: "São Paulo",
  AC: "Acre",
  AL: "Alagoas",
  AP: "Amapá",
  AM: "Amazonas",
  BA: "Bahia",
  CE: "Ceará",
  ES: "Espírito Santo",
  GO: "Goiás",
  MA: "Maranhão",
  MT: "Mato Grosso",
  MS: "Mato Grosso do Sul",
  MG: "Minas Gerais",
  PA: "Pará",
  PB: "Paraíba",
  PR: "Paraná",
  PE: "Pernambuco",
  PI: "Piauí",
  RJ: "Rio de Janeiro",
  RN: "Rio Grande do Norte",
  RS: "Rio Grande do Sul",
  RO: "Rondônia",
  RR: "Roraima",
  SC: "Santa Catarina",
  SE: "Sergipe",
  TO: "Tocantins",
  DF: "Distrito Federal",
};
export const HEAVY = {
  DEFAULT: "",
  RODOTREM: "Rodotrem",
  BITREM: "Bitrem",
  VANDERLEIA: "Vanderléia",
  CARRETA_LS: "Cerreta LS",
  CARRETA: "Carreta",
};
export const MEDIUM = {
  DEFAULT: "",
  BITRUCK: "Bitruck",
  TRUCK: "truck",
};
export const LIGHT = {
  DEFAULT: "",
  TOCO: "Toco",
  TRES_QUARTO: "3/4",
  VLC: "VLC",
  FURGOES: "Furgões",
};
export const BODYWORKOPEN = {
  DEFAULT: "",
  PLATAFORMA: "Plataforma",
  PRNCHA: "Prancha",
  CAÇAMBA: "Caçamba",
  GRANDE_ALTA_GRANELEIRA: "Grade alta Graneleira",
  GRANDE_BAIXA_CARGA_SECA: "Grade baixa Carga seca",
};
export const BODYWORKCLOSED = {
  DEFAULT: "",
  SIDEBAR: "Sider",
  BAU_FRIGORIFICA: "Baú frigorífico",
  BAU: "Baú",
};
export const BODYWORKSPECIAL = {
  DEFAULT: "",
  CAÇAMBA_BASCULANTE: "Caçamba basculante",
  CANAVIEIRA: "Canavieira",
  MUNCK: "Munck",
  FLORESTAL: "Florestal",
  BOIADEIRA: "Boiadeira",
  TANQUE: "Tanque",
  POLIGUNDASTE: "Poliguindaste",
};

//suport enums

export const SUPPORT_ENUM = {
  improperBilling: "Cobrança indevida",
  navigation: "Navegação",
  oboutOtherUsers: "Sobre outros usuários",
  doubt: "Duvidas",
  others: "Outros",
};
